name: Reusable Docker Build

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      dockerfile_path:
        required: false
        type: string
        default: '.'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show build information
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Image Name: ${{ inputs.image_name }}"
          echo "Image Tag: ${{ inputs.image_tag }}"
          echo "Dockerfile Path: ${{ inputs.dockerfile_path }}"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ inputs.image_name }}:${{ inputs.image_tag }} ${{ inputs.dockerfile_path }}

      - name: Push Docker image
        run: docker push ${{ inputs.image_name }}:${{ inputs.image_tag }}
