name: Reusable Docker Build

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
 
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: info
        run: |
          echo "User: ${{ github.actor }}"
          echo "Commit: ${{ github.sha }}"
          echo "Profile: https://github.com/${{ github.actor }}"
          echo "Workflow File: ${{ github.workflow }}"

          
      
