name: Reusable Docker Build

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
 
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        
      - name: Print all environment variables
        run: printenv

      - name: github-all
        run: echo '${{ toJson(github) }}'

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo commit SHA
        run: | 
          echo "Commit: ${{ github.sha }}"
          
      - name: Echo message
        run: | 
          echo "Commit: ${{ github.event.head_commit.message }}"
          
      - name: info
        run: |
          echo "User: ${{ github.event.sender.login }}"
          echo "Profile: https://github.com/${{ github.event.sender.avatar_url }}"
          echo "Workflow File: ${{ github.workflow }}"
          echo "Repository: ${{ github.repository }}"
          ORG_NAME="${{ github.repository_owner }}"
          REPO_NAME="${{ github.event.repository.name }}"
      


          
      
